export const regions = [
  {
    name: "Miền Bắc",
    cities: [
      "Hà Nội",
      "Hải Phòng",
      "Quảng Ninh",
      "Bắc Ninh",
      "Bắc Giang",
      "Hà Nam",
      "Hà Đông",
      "Hưng Yên",
      "Nam Định",
      "Ninh Bình",
      "Thái Bình",
      "Vĩnh Phúc",
      "Phú Thọ",
      "Yên Bái",
      "Tuyên Quang",
      "Lào Cai",
      "Lạng Sơn",
      "Bắc Kạn",
      "Cao Bằng",
      "Điện Biên",
      "Hòa Bình",
      "Lai Châu",
      "Sơn La",
    ],
  },
  {
    name: "Miền Trung",
    cities: [
      "Đà Nẵng",
      "Huế",
      "Quy Nhơn",
      "Quảng Trị",
      "Quảng Bình",
      "Quảng Nam",
      "Bình Định",
      "Phú Yên",
      "Khánh Hòa",
      "Ninh Thuận",
      "Bình Thuận",
      "Kon Tum",
      "Gia Lai",
      "Đắk Lắk",
      "Đắk Nông",
      "Lâm Đồng",
    ],
  },
  {
    name: "Miền Nam",
    cities: [
      "TP.HCM",
      "Cần Thơ",
      "Vũng Tàu",
      "Bình Dương",
      "Bình Phước",
      "Đồng Nai",
      "Tây Ninh",
      "Long An",
      "Đồng Tháp",
      "Tiền Giang",
      "An Giang",
      "Bến Tre",
      "Vĩnh Long",
      "Trà Vinh",
      "Hậu Giang",
      "Kiên Giang",
      "Sóc Trăng",
      "Bạc Liêu",
      "Cà Mau",
      "Hà Tiên",
      "Rạch Giá",
      "Cần Giờ",
    ],
  },
];
